### ISSUE TITLE
coArchi - Missing credentials provider

### ISSUE THREAD

**Issue by AlexanderNZ** [archimatetool/archi-modelrepository-plugin#166] opened 2021-04-12 02:29 UTC
Hi Folks,

I'm signing commits with GPG.
coArchi errors out when trying to commit - has anyone else experienced this before?

I'm not really sure if this is coArchi looking for gpg and not finding it, or something else. Does anyone know how I can collect more info on this? I've got signed commits setup on the private key I use to push changes in my model. Is there anything specific I need for coArchi here?

Error Log attached. Couldn't see anything suspicious but maybe I just missed something?
[archi_error_log.txt](https://github.com/archimatetool/archi-modelrepository-plugin/files/6293404/archi_error_log.txt)

### Version of Archi, Operating System
4.8.1

### Version of this plug-in
coArchi 0.71

### Any other plug-ins installed?
Nope

### Expected Behaviour
coArchi works with signed commits

### Actual Behaviour
When selecting OK in the commit dialog, an error message appears stating that the signing service is not available.

**Comment by Phillipus** [comment] 2021-04-12 08:40
GPG signing is not supported in coArchi. It may be something that we look at in a future version of coArchi.

I'll close this one as a duplicate of https://github.com/archimatetool/archi-modelrepository-plugin/issues/114

**Closed by Phillipus** 2021-04-12 08:40 UTC
