### ISSUE TITLE
Error after a branch delete

### ISSUE THREAD

**Issue by arnaudsp** [archimatetool/archi-modelrepository-plugin#137] opened 2020-05-18 13:15 UTC
### Version of Archi, Operating System
Archi Version 4.6.0 Build 201911111111

### Version of this plug-in
0.6.2.202004031233

### Any other plug-ins installed?
No

### Expected Behaviour
Normally, after the Branch's delete and a refresh, the branch disappear on all the computers.

### Actual Behaviour
The branch is still available on all the computer except for the user who delete the branch.

### Steps to Reproduce the Behaviour
1. User1 create the branch
2. User2 refresh the model and the new branch appears
3. User1 delete the branch and the branch is deleted
4. User2 continue to access to the branch deleted

**Comment by jbsarrodie** [comment] 2020-05-18 13:29
Hi,

>Normally, after the Branch's delete and a refresh, the branch disappear on all the computers.

This is not the expected behavior...

>The branch is still available on all the computer except for the user who delete the branch.

...this is the expected behavior.

This is exactly how it works with distributed version control systems: a branch is simply a kind of tag to easily find a specific version of your work, and deleting a branch simply means deleting your own tag. Of course, as soon as you share your branch by publishing it, you are no longuer the only one able to see this tag, and deleting it on the server simply has no impact on your colleagues' workstation.

That being said, there is a known bug on which Phil and I should work on soon: when a branch is deleted on the server, other people should no more see it as "Available" but as "Deleted" (or some similar status) but this doesn't work for the moment.

Once fixed, we might add some feature to hide or easily delete locally all "Deleted" branches, which in effect should be very similar to the behavior you'd like to have (but again, this is not the intended behavior at first).

**Comment by arnaudsp** [comment] 2020-05-18 13:38
Ok Thanks for your answer

**Comment by arnaudsp** [comment] 2020-05-18 13:57
Do you have a delivery date for the fix?

**Comment by jbsarrodie** [comment] 2020-05-18 14:03
>Do you have a delivery date for the fix?

Of course I was planning to work on it next month, but as you seem very enthusiastic and ask kindly to help us fix it I'm going to work all night long for nothing so that you can have it tomorrow morning....

May I remember you that Archi and coArchi are developped on a volontary basis my Phil and me. So everything we work on is delivered when it's ready, which means wen we have time and envy to work on it, nothing more nothing less.

Oh, and of course it is opensource, so if you're in a hurry don't hesitate to send us a patch.

Regards

**Comment by Phillipus** [comment] 2020-05-18 14:10
@arnaudsp Assuming the branch has actually been deleted on the server, the other users could also delete their copy of the branch. Did you try that?

**Comment by arnaudsp** [comment] 2020-05-18 14:18
@jbsarrodie Thank you for your answer it's just to have an idea...

@arnaudsp yes the other users can delete the branch but if they made a mistake they can republish on a deleted branch and recreate the branch

**Comment by jbsarrodie** [comment] 2020-05-18 14:19
@arnaudsp Sorry if I've been rude, but we've seen so many people asking Phil and I to fix something really urgent **for them** without ever wanted to support Archi a little, that I sometime feel the need to make it clear that Archi is run only by two guys doing their best. This is not a paid job, so we follow the "done when it's done" philosophy.

FWIW, it seems that a company is willing to fund this work, so the propability is higher than for some other things on the todo list.

**Comment by Phillipus** [comment] 2020-05-18 14:32
> yes the other users can delete the branch but if they made a mistake they can republish on a deleted branch and recreate the branch

They'll have to work around this for now until we address the issue. Remember from the front page [here](https://github.com/archimatetool/archi-modelrepository-plugin):

"This is an extension to Archi that allows collaborative work on Archi through sharing and versioning of models in a Repository. **It's a work in progress**."

:-)

**Comment by arnaudsp** [comment] 2020-05-18 14:42
Ok, Thx a lot for your answers

**Comment by Phillipus** [comment] 2020-08-13 08:36
This will be addressed in #140

**Closed by Phillipus** 2020-08-13 08:36 UTC
