### ISSUE TITLE
Forced commit on "Refresh Model"

### ISSUE THREAD

**Issue by timolaine** [archimatetool/archi-modelrepository-plugin#224] opened 2024-10-17 10:07 UTC
I am not sure this is actually a bug, but it is something that I do not completely understand. I am not sure what "Refresh Model" does.

I thought that "Refresh Model" just does a git pull, but apparently there is more to it. To me, it seems like some (all?) changes to the model actually require me to commit (not to push, just to commit) my changes as I do a Refresh.

### Version of Archi, Operating System

Windows

### Version of this plug-in

0.9.2

### Any other plug-ins installed?

jArchi

### Expected Behaviour

1. Refresh Model.
2. Make a small change to a model.
3. Refresh Model
4. Continue modelling without having to commit.

### Actual Behaviour

1. Refresh Model.
2. Make a small change to a model.
3. Refresh Model and be forced to commit along with the Refresh.
or
3. Commit
4. Refresh Model

### Steps to Reproduce the Behaviour
1. Refresh Model.
2. Make a small change to a model.
3. Refresh Model

**Comment by Phillipus** [comment] 2024-10-17 10:11
Hi, yes this is intended behaviour. Pending changes need to be committed first in order to "Refresh" which is a git pull and merge.

**Comment by timolaine** [comment] 2024-10-17 10:16
Thank you @Phillipus! I think this behaviour should be documented somewhere, at least in some condensed form. I had always thought that if you had no conflicts, there was no need to commit on Refresh. Perhaps the problem is that I don't understand Git itself that well, but I am quite sure that is common to many coArchi users.

**Comment by Phillipus** [comment] 2024-10-17 10:21
> I think this behaviour should be documented somewhere

If you think the wiki could be improved you are free to make a suggestion and/or edit it if you like.

**Comment by timolaine** [comment] 2024-10-17 10:27
Thank you, I updated [the documentation](https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Refresh-and-Publish). I hope my addition is correct.

**Comment by Phillipus** [comment] 2024-10-17 10:27
> Thank you, I updated [the documentation](https://github.com/archimatetool/archi-modelrepository-plugin/wiki/Refresh-and-Publish). I hope my addition is correct.

Thanks!

**Closed** 2024-12-21 15:20 UTC
