### ISSUE TITLE
Issue on Archi after installation the latest version 4.7.1

### ISSUE THREAD

**Issue by arnaudsp** [archimatetool/archi-modelrepository-plugin#143] opened 2020-08-07 09:20 UTC
After the installation of the new version of Archi 4.7.1, we try to use the collaboration plugins 0.6.2, and use the function "Import Remote model to Workspace", we encountered the error below:

![Archi Error](https://user-images.githubusercontent.com/63248899/89630622-ed3fc300-d89f-11ea-8a33-5e64560d0ac7.png)

### Version of Archi, Operating System
4.7.1 on windows 10
### Version of this plug-in
Collaboration version 0.6.2

### Any other plug-ins installed?
No

### Expected Behaviour
We can load normally the remote model
### Actual Behaviour
The import doesn't work
### Steps to Reproduce the Behaviour
1.Install Archi 4.7.1
2. Install Collaboration plugin 0.6.2
3. Use "Import Remote model to Workspace" function

**Comment by Phillipus** [comment] 2020-08-07 09:24
Sound like this issue - https://github.com/archimatetool/archi-modelrepository-plugin/issues/136

You could try to fix it using the script there.

**Comment by arnaudsp** [comment] 2020-08-07 12:39
We didn't have JArchi Script plugin, can you give us to allow us to apply the script?

**Comment by Phillipus** [comment] 2020-08-11 17:30
Closing as a duplicate of #136

**Closed by Phillipus** 2020-08-11 17:30 UTC
