### ISSUE TITLE
Unable to have multiple models in a repository?

### ISSUE THREAD

**Issue by scottwalkerwmda** [archimatetool/archi-modelrepository-plugin#168] opened 2021-05-07 10:39 UTC
Every time I try to add a new model to a repo, it is always trying overwriting the previous model. Meaning that I can only ever have one model in a repo.

Am I making a mistake or is this the intention?

**Comment by jbsarrodie** [comment] 2021-05-07 10:45
Hi, in coArchi, each model is stored into its own repository.

**Comment by Phillipus** [comment] 2021-05-07 11:27
I'll close this as this is intended behaviour.

**Closed by Phillipus** 2021-05-07 11:27 UTC
